### PR TITLE
Add groff ms format support to pagebreak.lua.

### PR DESCRIPTION
**Pull request by a-vrma**
The way {g,t}roff works is that the macro, `.bp`, has to be on a line by itself. Since we are creating a RawBlock, I think that is implied.

### CODE REVIEW

**Comment by tarleb** [comment]
Thanks! I'll merge once I have fixed the tests.

**Comment by tarleb** [comment]
It would be good to also update the README, as the change would add full support for groff ms AFAIU.

**Comment by a-vrma** [comment]
Updated README and added a test.

**Comment by tarleb** [comment]
Thanks!

**Pull request merged**
