### PR TITLE
support graphviz

### PR DESCRIPTION
**Pull request by muxueqz**
Hi, i write a simple lua filter for Rendering graphviz Code inside a markdown file in a Image. I hope the code was good enough for this collection (my first pull request).
--

Thx @floriandd2ba

### CODE REVIEW

**Comment by jgm** [comment]
floriandd2ba <notifications@github.com> writes:

> Write programs that do one thing and do it well.

The question is what counts as one thing.
We have one 'cat' program, for example, instead
of different ones for each file extension.

**Comment by SommerEngineering** [comment]
Dear @jgm and @muxueqz,

I can fix that too, along with my PR https://github.com/pandoc/lua-filters/pull/39. I do it as soon as possible.

**Comment by muxueqz** [comment]
@tarleb  I add graphviz to apt list, but CI: `Error: Unable to access jarfile /home/travis/plantuml.1.2018.9.jar`

**Comment by tarleb** [comment]
Seems to have been a temporary connectivity problem. Re-running the tests fixed it.

**Comment by tarleb** [comment]
Closing in favor of #39. Thank your for contributing @muxueqz, you are credited for the graphviz part of that filter.

**Pull request closed without merging**
