### PR TITLE
Added pandoc-zotxt.lua

### PR DESCRIPTION
**Pull request by odkr**
`pandoc-zotxt.lua` looks up sources of citations in Zotero and adds them either to a document's references metadata field or to a bibliography file.

### CODE REVIEW

**Comment by jgm** [comment]
Is there a way to work around this? E.g. a fake zotxt
that returns canned data? We can't check this in
without passing tests.

**Comment by odkr** [comment]
Hmm, not sure. I can't find an HTTP server in pure Lua. But maybe I can scrape something together from <http://lua-users.org/lists/lua-l/2002-04/msg00180.html> and [bnet](https://luapower.com/bnet). I'll have a look at it.

**Comment by jgm** [comment]
I don't want to make this too painful.
Why don't you just set it up so that the
test doesn't run by default, so it won't
register as a failure in our CI, and it
can still be run locally?

**Comment by odkr** [comment]
I wasn’t aware that with Python spinning up an HTTP server is as simple as saying `python3 -m http.server <portnumber>`. So I thought making the necessary changes wouldn't take much of an effort. That turned out to be wrong, of course. And tests still didn't work, no idea why. So, yes, I disable most of them now.

**Comment by jgm** [comment]
It looks like you accidentally checked in a large number of files in `lib/luarocks/rocks-5.3`?

**Comment by odkr** [comment]
Oh, I wasn’t aware that LuaUnit ships with that much documentation. I removed those files and others that were accidents.

**Comment by jgm** [comment]
Nothing that can be installed using luarocks should be included in the repository.  You can just have your test script install these, right?

**Comment by odkr** [comment]
Sure. Did I overlook some instructions to that effect? At any rate, I removed LuaUnit and the luarocks metadata for lunajson.

**Comment by odkr** [comment]
> [ -e "share/lua/5.3/luaunit.lua" ] || \
>		luarocks install --tree . luaunit
> /bin/sh: 2: luarocks: not found

So, I *can't* just have my test script install LuaUnit. I'll revert and re-commit, but not today.

**Comment by tarleb** [comment]
LuaUnit is a nice library, which we probably should be using in more places. Maybe we can add it in a central location like `.tools`?

**Comment by jgm** [comment]
Instead, let's just have our travis script install luarocks, so it will be available to everyone.

**Comment by odkr** [comment]
So, that didn’t work:

```
[ -e "share/lua/5.3/luaunit.lua" ] || \
		luarocks install --tree=. luaunit
Installing http://luarocks.org/repositories/rocks/luaunit-3.3-1.src.rock...
Using http://luarocks.org/repositories/rocks/luaunit-3.3-1.src.rock... switching to 'build' mode
Archive:  /tmp/luarocks_luarocks-rock-luaunit-3.3-1-5920/luaunit-3.3-1.src.rock
  inflating: luaunit-3.3-1.rockspec  
  inflating: rock-luaunit-3.3.zip    
  […]
Updating manifest for /home/travis/build/pandoc/lua-filters/pandoc-zotxt.lua/./lib/luarocks/rocks
No existing manifest. Attempting to rebuild...
luaunit 3.3-1 is now built and installed in /home/travis/build/pandoc/lua-filters/pandoc-zotxt.lua/./ (license: BSD)
mkdir -p "test/tmp"
rm -f "test/tmp"/*
pandoc --lua-filter "test/unit/test.lua" -o /dev/null \
		-M query-base-url=http://localhost:23120 \
		-M tests=test_core /dev/null || \
		{ EX=$?; sh test/scripts/httpdctl stop || :; exit "$EX"; }
Error running filter test/unit/test.lua:
[string "test/unit/test.lua"]:115: module 'luaunit' not found:
	no file 'luaunit.lua' in pandoc's datadir
	no field package.preload['luaunit']
	no file '/usr/local/share/lua/5.3/luaunit.lua'
	no file '/usr/local/share/lua/5.3/luaunit/init.lua'
	no file '/usr/local/lib/lua/5.3/luaunit.lua'
	no file '/usr/local/lib/lua/5.3/luaunit/init.lua'
	no file './luaunit.lua'
	no file './luaunit/init.lua'
	no file 'test/unit/../../share/lua/5.3/luaunit.lua'
	no file '/usr/local/lib/lua/5.3/luaunit.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './luaunit.so'
stack traceback:
	[C]: in function 'require'
	[string "test/unit/test.lua"]:115: in main chunk
make[1]: *** [test_core] Error 83
FAIL pandoc-zotxt.lua
```

The makefile works fine on my system though:

```shell
$ luarocks remove --tree=. luaunit
Checking stability of dependencies in the absence of
luaunit 3.3-1...

Removing luaunit 3.3-1...
Removal successful.
$ make test
[ -e "share/lua/5.3/luaunit.lua" ] || \
		luarocks install --tree=. luaunit
Installing https://luarocks.org/luaunit-3.3-1.src.rock

luaunit 3.3-1 is now installed in /Users/odin/repos/lua-filters/pandoc-zotxt.lua/. (license: BSD)

mkdir -p "test/tmp"
rm -f "test/tmp"/*
pandoc --lua-filter "test/unit/test.lua" -o /dev/null \
		-M query-base-url=http://localhost:23120 \
		-M tests=test_core /dev/null || \
		{ EX=$?; sh test/scripts/httpdctl stop || :; exit "$EX"; }
........
Ran 8 tests in 0.004 seconds, 8 successes, 0 failures
OK
pandoc --lua-filter "test/unit/get_input_directory-pwd.lua" </dev/null

for TEST in `find "test/unit/warn" -type f -name '*.lua' -exec basename \{\} \; | sed 's/.lua$//' | sort`; do \
		pandoc --lua-filter "test/unit/warn/$TEST.lua" -o /dev/null \
			/dev/null 2>"test/tmp/$TEST.out"; \
		cmp "test/norms/warn/$TEST.out" "test/tmp/$TEST.out"; \
	done
```

**Comment by jgm** [comment]
Presumably we need to set the LUA_PATH so it finds
these things?

**Comment by bpj** [comment]
But then you run the risk that other libraries installed elsewhere on the
user's system are not found properly, unless you can just add (prepend)
stuff to the variable in an OS neutral way. I vaguely remember you can,
having fought with that variable once.

Den ons 15 maj 2019 00:15John MacFarlane <notifications@github.com> skrev:

**Comment by odkr** [comment]
I don’t think LUA_PATH is the problem. `luarocks install -tree=. luaunit` should install LuaUnit relative to the current working directory, that is, in `./share/lua/5.3/luaunit.lua`. Well, at least that's what it does on my system. And the test suite adds that directory to `package.path`:

```lua
--- The path seperator of the operating system
local PATH_SEP = sub(package.config, 1, 1)

do
    local split_expr = '(.-' .. PATH_SEP .. '?)([^' .. PATH_SEP .. ']-)$'
    local san_exprs = {{PATH_SEP .. '%.' .. PATH_SEP, PATH_SEP},
        {PATH_SEP .. '+', PATH_SEP}, {'^%.' .. PATH_SEP, ''}}

    --- Splits a file's path into a directory and a filename part.
    --
    -- @tparam string path The path to the file.
    -- @treturn string The file's path.
    -- @treturn string The file's name.
    --
    -- This function makes an educated guess given the string it's passed.
    -- It doesn't look at the filesystem. The guess is educated enough though.
    function split_path (path)
        assert(path ~= '', 'path is the empty string')
        for _, s in ipairs(san_exprs) do path = path:gsub(unpack(s)) end
        local dir, fname = path:match(split_expr)
        dir = dir:gsub('(.)' .. PATH_SEP .. '$', '%1')
        if dir == '' then dir = '.' end
        if fname == '' then fname = '.' end
        return dir, fname
    end
end


--- The directory of the script.
local SCRIPT_DIR = split_path(PANDOC_SCRIPT_FILE)

--- The directory of the test suite.
local TEST_DIR = concat({SCRIPT_DIR, '..'}, PATH_SEP)

-- [...]

--- The repository directory.
local REPO_DIR = concat({TEST_DIR, '..'}, PATH_SEP)

package.path = package.path .. ';' ..
    concat({REPO_DIR, 'share', 'lua', '5.3', '?.lua'}, PATH_SEP)
```

Maybe something's wrong with this code then, I just don’t see what it could be.

**Comment by tarleb** [comment]
The filter is available at <https://github.com/odkr/pandoc-zotxt.lua>, which is much better than including it here. Thus closing.

**Pull request closed without merging**
