### PR TITLE
add escape char for '<' and ’>'

### PR DESCRIPTION
**Pull request by code-in-cpp**

### CODE REVIEW

**Comment by code-in-cpp** [comment]
This update is to fix below description

Content added inside of a <code> block is parsed as HTML by the web browser. If you have HTML characters (<>) in your code you will need to escape them ($lt; $gt;).

**Comment by code-in-cpp** [comment]
> _No description provided._

**Comment by tarleb** [comment]
Thanks for the PR! Why did you close it? Seems like a good fix for a real issue.

**Comment by code-in-cpp** [comment]
I am not familiar with PR and raised 2 same PR at one time, so I closed one

**Pull request closed without merging**
